"use client";

import { PageHeader } from "@/components/layout/PageHeader";
import { Footer } from "@/components/landing/Footer";

export default function Terms() {
  return (
    <main className="min-h-screen bg-white dark:bg-zinc-950">
      <PageHeader
        title="Terms of Service"
        description="Last Updated: February 7, 2026"
      />

      <section className="py-20">
        <div className="container mx-auto px-4 md:px-6">
          <div className="max-w-4xl mx-auto">
            {/* Document Container */}
            <div className="bg-white dark:bg-zinc-900 rounded-3xl p-8 md:p-12 shadow-xl border border-zinc-100 dark:border-zinc-800">

              <div className="prose dark:prose-invert prose-zinc prose-lg max-w-none font-sans">
                <p className="lead text-xl text-zinc-600 dark:text-zinc-400 font-medium leading-relaxed mb-12">
                  These Terms of Service constitute a legally binding agreement between you and Inspiro concerning your access to and use of the Service.
                </p>

                <div className="grid gap-12">

                  {/* Section 1 */}
                  <div className="border-b border-zinc-100 dark:border-zinc-800 pb-12">
                    <h2 className="text-2xl font-black text-zinc-900 dark:text-white tracking-tight mb-4">
                      1. Acceptance of Terms
                    </h2>
                    <p>
                      By downloading, installing, or using Inspiro, you agree to be bound by these Terms. If you disagree with any part of the terms, you may not access the Service.
                    </p>
                  </div>

                  {/* Section 2 */}
                  <div className="border-b border-zinc-100 dark:border-zinc-800 pb-12">
                    <h2 className="text-2xl font-black text-zinc-900 dark:text-white tracking-tight mb-4">
                      2. Use License
                    </h2>
                    <div className="bg-zinc-50 dark:bg-zinc-950/50 p-6 rounded-2xl border border-zinc-100 dark:border-zinc-800 mb-6">
                      <p className="mb-0 font-medium">
                        Inspiro is free to use for personal, non-commercial purposes.
                      </p>
                    </div>
                    <p>
                      You may share quotes generated by the app on social media or with friends, provided you do not claim ownership of the software itself.
                    </p>
                  </div>

                  {/* Section 3 */}
                  <div className="border-b border-zinc-100 dark:border-zinc-800 pb-12">
                    <h2 className="text-2xl font-black text-zinc-900 dark:text-white tracking-tight mb-4">
                      3. Disclaimer
                    </h2>
                    <p>
                        Inspiro is provided for entertainment and inspirational purposes only. It is not intended to provide medical, mental health, or professional advice.
                    </p>
                  </div>

                  {/* Section 4 */}
                  <div>
                    <h2 className="text-2xl font-black text-zinc-900 dark:text-white tracking-tight mb-4">
                      4. Contact Us
                    </h2>
                    <p>
                      In order to resolve a complaint regarding the Site or to receive further information regarding use of the Site, please contact us at:
                    </p>
                    <a href="mailto:hello@inspiro.app" className="inline-flex items-center gap-2 text-brand-600 dark:text-brand-400 font-bold no-underline hover:underline">
                      hello@inspiro.app
                    </a>
                  </div>

                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </main>
  );
}
